service: crud-test

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${self:custom.settings.REGION}
  profile: serverless
  endpointType: regional
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_TABLE}"

custom:
  settings:
    POSTS_TABLE: posts
    REGION: ap-south-1
  # webpack:
  #   webpackConfig: "webpack.config.js" # Name of webpack configuration file
  #   includeModules: false # Node modules configuration for packaging
  #   packager: "npm" # Packager that will be used to package your external modules

plugins:
  - serverless-webpack

package:
  individually: true
  # exclude:
  #   - node_modules/**
  # - webpack.config.js
  # - package.json
  # - package-lock.json
  # - functions/**

functions:
  hello:
    handler: functions/hello.function
    events:
      - httpApi:
          path: /hello
          method: get
  createPost:
    handler: functions/create.function
    events:
      - httpApi:
          path: /post
          method: post
  getAllPosts:
    handler: functions/getAll.function
    events:
      - httpApi:
          path: /posts
          method: get
  getPost:
    handler: functions/get.function
    events:
      - httpApi:
          path: /post/{id}
          method: get
  updatePost:
    handler: functions/update.function
    events:
      - httpApi:
          path: /post/{id}
          method: put
  deletePost:
    handler: functions/delete.function
    events:
      - httpApi:
          path: /post/{id}
          method: delete

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"
        TableName: ${self:custom.settings.POSTS_TABLE}
